name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - uses: actions/checkout@v4

    # Set up JDK 11 for the project
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    # Install sbt
    - name: Install sbt
      run: |
        echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
        curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x99E82A75642AC823" | sudo apt-key add
        sudo apt-get update
        sudo apt-get install sbt

    # Change working directory to StringPatternMatching
    - name: Change directory to StringPatternMatching
      working-directory: ./StringPatternMatching
      run: echo "Working in ./StringPatternMatching"

    # Run tests 
    - name: Run tests
      working-directory: ./StringPatternMatching
      run: sbt test

    # Upload dependency graph (running sbt task)
    # Uncomment if required
    # - name: Upload dependency graph
    #   working-directory: ./StringPatternMatching
    #   run: sbt dependencySubmission
