name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - uses: actions/checkout@v4

    # Step 2: Change working directory to StringPatternMatching
    - name: Change directory to StringPatternMatching
      working-directory: ./StringPatternMatching
      run: echo "Working in ./StringPatternMatching"

    # Step 3: Set up JDK 11 for the project
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'

    # Step 4: Run tests 
    - name: Run tests
      working-directory: ./StringPatternMatching
      run: sbt test

    # Step 5: Upload dependency graph (running sbt task)
 #   - name: Upload dependency graph
  #    working-directory: ./StringPatternMatching
   #   run: sbt dependencySubmission
